import { Response, Router } from "express";
import type { User } from "@tsw/prisma";
import { AuthenticatedRequest, requireAuth } from "../middleware/auth";
import { aiService } from "../services/aiService";
import { coachAgentService } from "../services/coach/agent";
import { toCoachConversationHistory } from "../services/coachConversationHistoryService";
import { deriveCoachAttentionItems } from "../services/coachAttentionService";
import { getCoachPersonalityConfig } from "../services/coachPersonalityService";
import { notificationService } from "../services/notificationService";
import { cancelPendingPlanCreationProposals } from "../services/planCreationProposalStatusService";
import { logger } from "../utils/logger";
import { prisma } from "../utils/prisma";
import { supermemoryService } from "../services/supermemoryService";
import { coachResponseStatusService } from "../services/coachResponseStatusService";

const router = Router();

type CoachResponseStatus = "thinking" | "searching" | "browsing" | "drafting";
type ImageAttachment = {
  id?: string;
  url: string;
  mediaType: string;
  filename?: string;
};
type ConversationHistory = Array<{
  role: "system" | "user" | "assistant";
  content: string;
  imageAttachments?: ImageAttachment[];
}>;

const MAX_COACH_IMAGE_ATTACHMENTS = 4;
const MAX_COACH_IMAGE_DATA_URL_LENGTH = 1_600_000;

class RouteError extends Error {
  constructor(
    public statusCode: number,
    message: string
  ) {
    super(message);
  }
}

// Plans past their finishingDate stay included so attention items can drive
// them to a decision (renew or archive).
function activePlanWhere(_now: Date) {
  return {
    deletedAt: null,
    archivedAt: null,
    isPaused: false,
  };
}

function writeSseEvent(res: Response, event: string, data: unknown) {
  res.write(`event: ${event}\n`);
  res.write(`data: ${JSON.stringify(data)}\n\n`);
}

function normalizeImageAttachments(value: unknown): ImageAttachment[] {
  if (value === undefined || value === null) return [];
  if (!Array.isArray(value)) {
    throw new RouteError(400, "Image attachments must be an array");
  }
  if (value.length > MAX_COACH_IMAGE_ATTACHMENTS) {
    throw new RouteError(400, `Attach up to ${MAX_COACH_IMAGE_ATTACHMENTS} images`);
  }

  return value.map((attachment, index) => {
    if (!attachment || typeof attachment !== "object") {
      throw new RouteError(400, "Invalid image attachment");
    }

    const data = attachment as Record<string, unknown>;
    const url = typeof data.url === "string" ? data.url : "";
    const mediaType =
      typeof data.mediaType === "string" ? data.mediaType : "";
    const filename =
      typeof data.filename === "string" ? data.filename : undefined;
    const id = typeof data.id === "string" ? data.id : `image-${index + 1}`;

    if (!url.startsWith("data:image/")) {
      throw new RouteError(400, "Only data URL image attachments are supported");
    }
    if (!mediaType.startsWith("image/")) {
      throw new RouteError(400, "Only image attachments are supported");
    }
    if (url.length > MAX_COACH_IMAGE_DATA_URL_LENGTH) {
      throw new RouteError(400, "Attached image is too large");
    }

    return { id, url, mediaType, filename };
  });
}

function serializeSystemMessage(
  systemMessage: Awaited<ReturnType<typeof prisma.message.create>>
) {
  return {
    id: systemMessage.id,
    chatId: systemMessage.chatId,
    role: systemMessage.role,
    content: systemMessage.content,
    createdAt: systemMessage.createdAt,
  };
}

function serializeUserMessage(
  userMessage: Awaited<ReturnType<typeof prisma.message.create>>,
  user: User
) {
  const metadata =
    userMessage.metadata && typeof userMessage.metadata === "object"
      ? (userMessage.metadata as any)
      : null;

  return {
    id: userMessage.id,
    chatId: userMessage.chatId,
    role: userMessage.role,
    content: userMessage.content,
    imageAttachments: metadata?.imageAttachments || null,
    createdAt: userMessage.createdAt,
    senderId: user.id,
    senderName: user.name,
    senderPicture: user.picture,
  };
}

function buildCoachAttentionSystemMessage(
  item: {
    title: string;
    message: string;
    facts: Array<{ label: string; value: string }>;
  },
  guidance?: string
) {
  const facts = item.facts
    .map((fact) => `${fact.label}: ${fact.value}`)
    .join("; ");

  return [
    "APP_TRIGGERED_PLAN_ATTENTION_ACTION",
    "",
    "The user opened a plan update action generated by the app. This was not typed by the user.",
    guidance ? `The user selected this direction: ${guidance}` : "",
    "",
    "Attention item:",
    item.title,
    item.message,
    `Facts: ${facts}`,
    "",
    "Respond as the coach. Present the next useful adaptation for the affected plan. If the right next week is clear, use the plan modification tool to propose concrete dated sessions. If the direction is unclear, ask exactly one concise question with common options.",
  ].filter(Boolean).join("\n");
}

async function updateCoachResponseStatus(input: {
  chatId: string;
  userMessageId: string;
  state: CoachResponseStatus;
  sendStatus?: (state: CoachResponseStatus) => void;
}) {
  input.sendStatus?.(input.state);
  await coachResponseStatusService.updateStatus({
    chatId: input.chatId,
    userMessageId: input.userMessageId,
    status: input.state,
  });
}

async function runCoachV2MessagePipeline(params: {
  user: User;
  chat: { id: string; title: string | null };
  chatId: string;
  message: string;
  messageRole?: "user" | "system";
  imageAttachments?: ImageAttachment[];
  serializedUserMessage: Record<string, unknown>;
  conversationHistory?: ConversationHistory;
  onStatus?: (status: CoachResponseStatus) => void | Promise<void>;
  logLabel: string;
}) {
  const {
    user,
    chat,
    chatId,
    message,
    messageRole = "user",
    imageAttachments,
    serializedUserMessage,
    onStatus,
    logLabel,
  } = params;
  let conversationHistory = params.conversationHistory;

  if (!conversationHistory) {
    const currentMessageId =
      typeof serializedUserMessage.id === "string"
        ? serializedUserMessage.id
        : null;
    const history = await prisma.message.findMany({
      where: {
        chatId,
        ...(currentMessageId ? { id: { not: currentMessageId } } : {}),
      },
      orderBy: { createdAt: "desc" },
      take: 20,
    });
    history.reverse();
    conversationHistory = toCoachConversationHistory(history);
  }

  const plans = await prisma.plan.findMany({
    where: {
      userId: user.id,
      deletedAt: null,
      archivedAt: null,
      isPaused: false,
      OR: [
        { finishingDate: null },
        { finishingDate: { gt: new Date() } },
      ],
    },
    include: {
      activities: true,
      sessions: true,
      milestones: true,
    },
    orderBy: [{ createdAt: "desc" }],
  });

  const memoryQuery =
    message.trim() ||
    (imageAttachments?.length ? "User attached an image for the coach to inspect." : "");
  const memoriesContext = await supermemoryService.getProfile(user.id, memoryQuery);

  const v2Response = await coachAgentService.generateResponse({
    user,
    message,
    messageRole,
    imageAttachments,
    conversationHistory,
    plans: plans as Array<typeof plans[0] & {
      sessions: Array<{ id: string; planId: string; activityId: string; date: Date; quantity: number; descriptiveGuide: string; isCoachSuggested: boolean; createdAt: Date; imageUrls: string[] }>;
      milestones: Array<{ id: string; planId: string; date: Date; description: string; progress: number | null; criteria: unknown; createdAt: Date }>;
    }>,
    memoriesContext,
    onStatus,
    reportContext: {
      source: logLabel,
      chatId,
    },
  });

  const savedMessages: Awaited<ReturnType<typeof prisma.message.create>>[] = [];
  const hasNewPlanCreationProposal = v2Response.draftMessages.some(
    (draft) => (draft.planCreationProposals?.length || 0) > 0
  );
  for (const draft of v2Response.draftMessages) {
    const coachMsg = await prisma.message.create({
      data: {
        chatId,
        role: "COACH",
        content: draft.content,
        metadata: {
          planReplacements: draft.planReplacements || [],
          planProposals: JSON.parse(JSON.stringify(draft.planProposals || [])),
          planCreationProposals: JSON.parse(JSON.stringify(draft.planCreationProposals || [])),
          activityLogProposals: JSON.parse(JSON.stringify(draft.activityLogProposals || [])),
          activityEditProposals: JSON.parse(JSON.stringify(draft.activityEditProposals || [])),
          userContextEventProposals: JSON.parse(JSON.stringify(draft.userContextEventProposals || [])),
          ...(draft.toolCalls && {
            toolCalls: JSON.parse(JSON.stringify(draft.toolCalls)),
          }),
          ...(draft.error && { error: true }),
        },
      },
    });
    savedMessages.push(coachMsg);
  }

  if (hasNewPlanCreationProposal) {
    await cancelPendingPlanCreationProposals(
      chatId,
      savedMessages.map((message) => message.id)
    );
  }

  await prisma.chat.update({
    where: { id: chatId },
    data: { updatedAt: new Date() },
  });

  const fullCoachText = v2Response.draftMessages.map((d) => d.content).join("\n");
  const lastSavedMessage = savedMessages[savedMessages.length - 1];
  if (lastSavedMessage) {
    supermemoryService.addMemory(
      user.id,
      `${messageRole === "system" ? "system" : "user"}: ${memoryQuery}\nassistant: ${fullCoachText}`,
      lastSavedMessage.id
    );
  }

  logger.info(
    `${logLabel} - User: ${user.username}, Message: "${message.substring(0, 50)}...", Drafts: ${savedMessages.length}`
  );

  if (!chat.title) {
    (async () => {
      try {
        const titlePrompt = `${messageRole === "system" ? "System" : "User"}: ${message}\nCoach: ${fullCoachText}`;
        const titleSystemPrompt =
          "You are a chat title generator. Create a very brief title (3-5 words max) that summarizes the topic of this conversation. " +
          "The title should be clear and concise. Only output the title, nothing else.";

        const generatedTitle = await aiService.generateText({
          prompt: titlePrompt,
          systemPrompt: titleSystemPrompt,
        });

        await prisma.chat.update({
          where: { id: chatId },
          data: { title: generatedTitle.trim() },
        });

        logger.info(
          `Generated title for chat ${chatId}: "${generatedTitle}"`
        );
      } catch (error) {
        logger.error("Error generating chat title:", error);
      }
    })();
  }

  const resolvedMessages = savedMessages.map((coachMsg, idx) => {
    const draft = v2Response.draftMessages[idx];
    const resolvedPlanReplacements =
      draft.planReplacements
        ?.map((replacement) => {
          const plan = plans.find(
            (p) =>
              p.goal.toLowerCase() === replacement.planGoal.toLowerCase()
          );
          return plan
            ? {
                textToReplace: replacement.textToReplace,
                plan: {
                  id: plan.id,
                  goal: plan.goal,
                  emoji: plan.emoji,
                },
              }
            : null;
        })
        .filter(Boolean) || [];

    return {
      id: coachMsg.id,
      chatId: coachMsg.chatId,
      role: coachMsg.role,
      content: draft.content,
      planReplacements: resolvedPlanReplacements,
      planProposals: draft.planProposals || [],
      planCreationProposals: draft.planCreationProposals || [],
      activityLogProposals: draft.activityLogProposals || [],
      activityEditProposals: draft.activityEditProposals || [],
      userContextEventProposals: draft.userContextEventProposals || [],
      toolCalls: draft.toolCalls || null,
      error: draft.error || false,
      createdAt: coachMsg.createdAt,
    };
  });

  return {
    userMessage: serializedUserMessage,
    messages: [serializedUserMessage, ...resolvedMessages],
    message: resolvedMessages[resolvedMessages.length - 1] || serializedUserMessage,
  };
}

async function prepareCoachMessageRewrite(params: {
  user: User;
  chatId: string;
  messageId: string;
  message: string;
}) {
  const { user, chatId, messageId, message } = params;

  const chat = await prisma.chat.findFirst({
    where: {
      id: chatId,
      userId: user.id,
      type: "COACH",
    },
  });

  if (!chat) {
    throw new RouteError(404, "Chat not found");
  }

  const coachChatWhere = {
    userId: user.id,
    type: "COACH" as const,
  };

  const targetMessage = await prisma.message.findFirst({
    where: {
      id: messageId,
      role: "USER",
      senderId: user.id,
      chat: coachChatWhere,
    },
    include: {
      chat: {
        select: {
          id: true,
          title: true,
        },
      },
    },
  });

  if (!targetMessage) {
    throw new RouteError(404, "Editable message not found");
  }

  const targetMetadata = targetMessage.metadata as any;
  if (targetMetadata?.userAction) {
    throw new RouteError(400, "Action messages cannot be edited");
  }

  const history = await prisma.message.findMany({
    where: {
      chat: coachChatWhere,
      createdAt: { lt: targetMessage.createdAt },
    },
    orderBy: { createdAt: "desc" },
    take: 20,
  });
  history.reverse();

  await prisma.message.deleteMany({
    where: {
      chat: coachChatWhere,
      createdAt: { gte: targetMessage.createdAt },
    },
  });

  const userMessage = await prisma.message.create({
    data: {
      chatId: targetMessage.chatId,
      role: "USER",
      content: message,
      senderId: user.id,
    },
  });

  return {
    chat: targetMessage.chat,
    conversationHistory: toCoachConversationHistory(history),
    serializedUserMessage: serializeUserMessage(userMessage, user),
  };
}

// Get all chats for the current user (COACH, DIRECT, GROUP)
router.get(
  "/",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    try {
      const user = req.user!;
      const coachPersonality = getCoachPersonalityConfig(user.coachPersonality);

      // Fetch all chats where user is involved
      const chats = await prisma.chat.findMany({
        where: {
          OR: [
            // Coach chats
            { userId: user.id, type: "COACH" },
            // Direct chats where user is a participant
            {
              type: "DIRECT",
              participants: {
                some: { userId: user.id },
              },
            },
            // Group chats where user is a participant
            {
              type: "GROUP",
              participants: {
                some: { userId: user.id },
              },
            },
          ],
        },
        include: {
          participants: {
            include: {
              user: {
                select: {
                  id: true,
                  name: true,
                  username: true,
                  picture: true,
                },
              },
            },
          },
          planGroup: {
            select: {
              id: true,
            },
          },
          messages: {
            orderBy: { createdAt: "desc" },
            take: 1,
            select: {
              content: true,
              createdAt: true,
              role: true,
            },
          },
        },
        orderBy: { updatedAt: "desc" },
      });

      // Transform chats to include useful information
      // Only the latest coach chat should report unread count
      const latestCoachChatId = chats.find((c) => c.type === "COACH")?.id;

      const transformedChats = await Promise.all(
        chats.map(async (chat) => {
          const lastMessage = chat.messages[0];

          // Count unread messages
          // For coach chats, use readAt-based counting (only latest chat)
          // For other chats, use status-based counting
          let unreadCount = 0;
          if (chat.type === "COACH") {
            if (chat.id === latestCoachChatId) {
              unreadCount = await prisma.message.count({
                where: {
                  chatId: chat.id,
                  role: "COACH",
                  readAt: null,
                },
              });
            }
          } else {
            unreadCount = await prisma.message.count({
              where: {
                chatId: chat.id,
                status: "SENT",
                senderId: { not: user.id },
              },
            });
          }

          return {
            id: chat.id,
            type: chat.type,
            title: chat.title,
            createdAt: chat.createdAt,
            updatedAt: chat.updatedAt,
            coachId: chat.coachId,
            planGroupId: chat.planGroupId,
            unreadCount,
            participants: chat.participants.map((p) => ({
              id: p.id,
              userId: p.user.id,
              name: p.user.name,
              username: p.user.username,
              picture: p.user.picture,
              joinedAt: p.joinedAt,
              leftAt: p.leftAt,
            })),
            lastMessage: lastMessage
              ? {
                  content: lastMessage.content,
                  createdAt: lastMessage.createdAt,
                  // For group chats, we'd need to fetch sender name
                  senderName:
                    lastMessage.role === "USER" ? user.name : coachPersonality.displayName,
                }
              : undefined,
          };
        })
      );

      logger.info(`Fetched ${chats.length} chats for user ${user.username}`);

      res.json({ chats: transformedChats });
    } catch (error) {
      logger.error("Error fetching chats:", error);
      res.status(500).json({ error: "Failed to fetch chats" });
    }
  }
);

router.post(
  "/coach/attention/start",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    try {
      const user = req.user!;
      const { dedupeKey, guidance } = req.body;

      if (!dedupeKey || typeof dedupeKey !== "string") {
        return res.status(400).json({ error: "dedupeKey is required" });
      }
      if (guidance !== undefined && typeof guidance !== "string") {
        return res.status(400).json({ error: "guidance must be a string" });
      }

      const now = new Date();
      const plans = await prisma.plan.findMany({
        where: {
          userId: user.id,
          ...activePlanWhere(now),
        },
        include: { activities: true, sessions: true, milestones: true },
        orderBy: [{ createdAt: "desc" }],
      });
      const attentionItems = deriveCoachAttentionItems({ user, plans, now });
      const attentionItem = attentionItems.find(
        (item) => item.dedupeKey === dedupeKey
      );

      if (!attentionItem) {
        return res.status(409).json({
          error: "This plan update is no longer active",
        });
      }

      const coachPersonality = getCoachPersonalityConfig(user.coachPersonality);
      let coach = await prisma.coach.findFirst({
        where: { ownerId: user.id },
      });

      if (!coach) {
        coach = await prisma.coach.create({
          data: {
            ownerId: user.id,
            details: {
              name: coachPersonality.displayName,
              bio: `Your personal AI coach helping you achieve your goals as ${coachPersonality.title}.`,
            },
          },
        });
      }

      let chat = await prisma.chat.findFirst({
        where: { userId: user.id, type: "COACH" },
        orderBy: { updatedAt: "desc" },
      });

      if (!chat) {
        chat = await prisma.chat.create({
          data: {
            userId: user.id,
            coachId: coach.id,
            type: "COACH",
            title: null,
          },
        });
      }

      const history = await prisma.message.findMany({
        where: { chatId: chat.id },
        orderBy: { createdAt: "desc" },
        take: 20,
      });
      history.reverse();

      const systemContent = buildCoachAttentionSystemMessage(attentionItem, guidance);
      const systemMessage = await prisma.message.create({
        data: {
          chatId: chat.id,
          role: "SYSTEM",
          content: systemContent,
          metadata: {
            source: "coach_attention",
            coachAttentionItems: [attentionItem],
          },
        },
      });

      const payload = await runCoachV2MessagePipeline({
        user,
        chat,
        chatId: chat.id,
        message: systemContent,
        messageRole: "system",
        serializedUserMessage: serializeSystemMessage(systemMessage),
        conversationHistory: toCoachConversationHistory(history),
        logLabel: "Coach attention action",
      });

      res.json({
        chat,
        systemMessageId: systemMessage.id,
        messages: payload.messages.filter((message) => message.role !== "SYSTEM"),
      });
    } catch (error) {
      logger.error("Error starting coach attention action:", error);
      res.status(500).json({ error: "Failed to start coach attention action" });
    }
  }
);

// Get messages for a specific chat
router.get(
  "/:chatId/messages",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    try {
      const user = req.user!;
      const { chatId } = req.params;
      const includeCoachHistory = req.query.includeCoachHistory === "true";

      // Verify user has access to this chat
      const chat = await prisma.chat.findFirst({
        where: {
          id: chatId,
          OR: [
            // User owns the coach chat
            { userId: user.id, type: "COACH" },
            // User is a participant
            {
              participants: {
                some: { userId: user.id },
              },
            },
          ],
        },
        include: {
          participants: {
            include: {
              user: {
                select: {
                  id: true,
                  name: true,
                  username: true,
                  picture: true,
                },
              },
            },
          },
        },
      });

      if (!chat) {
        return res.status(404).json({ error: "Chat not found" });
      }

      // Fetch all messages for this chat. The AI coach can use long-term memory
      // across coach chats, so the frontend can request the same visible timeline.
      const messages = await prisma.message.findMany({
        where:
          chat.type === "COACH" && includeCoachHistory
            ? {
                chat: {
                  userId: user.id,
                  type: "COACH",
                },
              }
            : {
                chatId: chatId,
              },
        include: {
          feedback: true,
          sender: {
            select: {
              id: true,
              name: true,
              username: true,
              picture: true,
            },
          },
        },
        orderBy: { createdAt: "asc" },
      });

      // For coach chats, we need to parse and structure messages (same logic as ai.ts)
      if (chat.type === "COACH") {
        const visibleMessages = messages.filter((msg) => msg.role !== "SYSTEM");
        const plans = await prisma.plan.findMany({
          where: {
            userId: user.id,
            deletedAt: null,
          },
        });

        const metrics = await prisma.metric.findMany({
          where: {
            userId: user.id,
          },
        });

        const stripEmojis = (text: string) => {
          return text
            .replace(
              /[\p{Emoji}\p{Emoji_Presentation}\p{Emoji_Modifier}\p{Emoji_Component}]/gu,
              ""
            )
            .trim();
        };

        const structuredMessages = visibleMessages.map((msg) => {
          if (msg.role === "COACH") {
            if (msg.metadata && typeof msg.metadata === "object") {
              const metadata = msg.metadata as any;

              const planReplacements =
                metadata.planReplacements
                  ?.map((replacement: any) => {
                    const plan = plans.find(
                      (p: any) =>
                        p.goal.toLowerCase() ===
                        replacement.planGoal.toLowerCase()
                    );
                    return plan
                      ? {
                          textToReplace: replacement.textToReplace,
                          plan: {
                            id: plan.id,
                            goal: plan.goal,
                            emoji: plan.emoji,
                          },
                        }
                      : null;
                  })
                  .filter(Boolean) || [];

              let metricReplacement: any = null;
              if (metadata.metricReplacement) {
                const aiMetricTitle = stripEmojis(
                  metadata.metricReplacement.metricTitle
                ).toLowerCase();
                const metric = metrics.find(
                  (m: any) =>
                    stripEmojis(m.title).toLowerCase() === aiMetricTitle
                );
                if (metric) {
                  metricReplacement = {
                    textToReplace: metadata.metricReplacement.textToReplace,
                    rating: metadata.metricReplacement.rating,
                    metric: {
                      id: metric.id,
                      title: metric.title,
                      emoji: metric.emoji,
                    },
                    status: metadata.metricReplacement.status || null,
                  };
                }
              }

              return {
                id: msg.id,
                chatId: msg.chatId,
                role: msg.role,
                content: msg.content,
                status: msg.status,
                planReplacements,
                metricReplacement,
                planProposals: metadata.planProposals || [],
                planCreationProposals: metadata.planCreationProposals || [],
                activityLogProposals: metadata.activityLogProposals || [],
                activityEditProposals: metadata.activityEditProposals || [],
                userContextEventProposals: metadata.userContextEventProposals || [],
                coachAttentionItems: metadata.coachAttentionItems || [],
                userRecommendations: metadata.userRecommendations || null,
                toolCalls: metadata.toolCalls || null,
                error: metadata.error || false,
                source: metadata.source || null,
                createdAt: msg.createdAt,
                feedback: msg.feedback,
              };
            }

            // Fallback for old format or parsing
            return {
              id: msg.id,
              chatId: msg.chatId,
              role: msg.role,
              content: msg.content,
              status: msg.status,
              planReplacements: [],
              metricReplacement: null,
              userContextEventProposals: [],
              toolCalls: null,
              error: false,
              createdAt: msg.createdAt,
              feedback: msg.feedback,
            };
          }

          // USER messages
          const metadata =
            msg.metadata && typeof msg.metadata === "object"
              ? (msg.metadata as any)
              : null;
          return {
            id: msg.id,
            chatId: msg.chatId,
            role: msg.role,
            content: msg.content,
            status: msg.status,
            userAction: metadata?.userAction || null,
            imageAttachments: metadata?.imageAttachments || null,
            createdAt: msg.createdAt,
            feedback: msg.feedback,
          };
        });

        return res.json({ messages: structuredMessages });
      }

      // For DIRECT and GROUP chats, return messages with sender information
      const structuredMessages = messages.map((msg) => {
        const metadata =
          msg.metadata && typeof msg.metadata === "object"
            ? (msg.metadata as any)
            : null;

        return {
          id: msg.id,
          chatId: msg.chatId,
          role: msg.role,
          content: msg.content,
          status: msg.status,
          imageAttachments: metadata?.imageAttachments || null,
          createdAt: msg.createdAt,
          senderId: msg.senderId,
          senderName: msg.sender?.name,
          senderPicture: msg.sender?.picture,
        };
      });

      logger.info(
        `Fetched ${messages.length} messages for chat ${chatId}, user ${user.username}`
      );

      res.json({ messages: structuredMessages });
    } catch (error) {
      logger.error("Error fetching messages:", error);
      res.status(500).json({ error: "Failed to fetch messages" });
    }
  }
);

router.get(
  "/:chatId/coach-response-status",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    try {
      const user = req.user!;
      const { chatId } = req.params;

      const chat = await prisma.chat.findFirst({
        where: {
          id: chatId,
          userId: user.id,
          type: "COACH",
        },
        select: { id: true },
      });

      if (!chat) {
        return res.status(404).json({ error: "Coach chat not found" });
      }

      const status = await coachResponseStatusService.getByChat(chatId);
      res.json({ status });
    } catch (error) {
      logger.error("Error fetching coach response status:", error);
      res.status(500).json({ error: "Failed to fetch coach response status" });
    }
  }
);

router.post(
  "/:chatId/messages/stream",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    let streamStarted = false;
    let clientClosed = false;
    let statusUserMessageId: string | null = null;

    try {
      const user = req.user!;
      const { chatId } = req.params;
      const { message, coachVersion } = req.body;
      const messageText = typeof message === "string" ? message : "";
      const imageAttachments = normalizeImageAttachments(req.body.imageAttachments);
      const hasMessageText = messageText.trim().length > 0;

      if (!hasMessageText && imageAttachments.length === 0) {
        return res.status(400).json({ error: "Message or image is required" });
      }

      if (coachVersion !== "v2") {
        return res.status(400).json({ error: "Streaming is only available for coach v2" });
      }

      const chat = await prisma.chat.findFirst({
        where: {
          id: chatId,
          userId: user.id,
          type: "COACH",
        },
        include: {
          coach: true,
          participants: true,
        },
      });

      if (!chat) {
        return res.status(404).json({ error: "Coach chat not found" });
      }

      res.setHeader("Content-Type", "text/event-stream");
      res.setHeader("Cache-Control", "no-cache, no-transform");
      res.setHeader("Connection", "keep-alive");
      res.flushHeaders?.();
      streamStarted = true;

      req.on("close", () => {
        clientClosed = true;
      });

      const sendStatus = (state: CoachResponseStatus) => {
        if (!clientClosed) {
          writeSseEvent(res, "status", { state });
        }
      };

      const userMessage = await prisma.message.create({
        data: {
          chatId,
          role: "USER",
          content: messageText,
          senderId: user.id,
          ...(imageAttachments.length && {
            metadata: {
              imageAttachments,
            },
          }),
        },
      });
      const serializedUserMessage = serializeUserMessage(userMessage, user);
      statusUserMessageId = userMessage.id;

      await coachResponseStatusService.start({
        chatId,
        userMessageId: statusUserMessageId,
        status: "thinking",
      });
      sendStatus("thinking");

      await prisma.chat.update({
        where: { id: chatId },
        data: { updatedAt: new Date() },
      });

      const payload = await runCoachV2MessagePipeline({
        user,
        chat,
        chatId,
        message: messageText,
        imageAttachments,
        serializedUserMessage,
        onStatus: (state) =>
          updateCoachResponseStatus({
            chatId,
            userMessageId: statusUserMessageId!,
            state,
            sendStatus,
          }),
        logLabel: "Coach v2 stream chat",
      });

      await coachResponseStatusService.complete({
        chatId,
        userMessageId: statusUserMessageId,
      });

      if (!clientClosed) {
        writeSseEvent(res, "done", payload);
        res.end();
      }
    } catch (error) {
      logger.error("Error streaming coach message:", error);
      if (error instanceof RouteError && !streamStarted) {
        return res.status(error.statusCode).json({ error: error.message });
      }
      if (statusUserMessageId) {
        await coachResponseStatusService.markError({
          chatId: req.params.chatId,
          userMessageId: statusUserMessageId,
          errorMessage: "Failed to send message",
        });
      }
      if (streamStarted && !clientClosed) {
        writeSseEvent(res, "error", { error: "Failed to send message" });
        res.end();
        return;
      }
      res.status(500).json({ error: "Failed to send message" });
    }
  }
);

// Send a message to any chat type
router.post(
  "/:chatId/messages",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    try {
      const user = req.user!;
      const { chatId } = req.params;
      const { message, coachVersion } = req.body;
      const messageText = typeof message === "string" ? message : "";
      const imageAttachments = normalizeImageAttachments(req.body.imageAttachments);
      const hasMessageText = messageText.trim().length > 0;

      if (!hasMessageText && imageAttachments.length === 0) {
        return res.status(400).json({ error: "Message or image is required" });
      }

      const useV2Coach = coachVersion === "v2";

      // Verify user has access to this chat
      const chat = await prisma.chat.findFirst({
        where: {
          id: chatId,
          OR: [
            { userId: user.id, type: "COACH" },
            {
              participants: {
                some: { userId: user.id },
              },
            },
          ],
        },
        include: {
          coach: true,
          participants: true,
        },
      });

      if (!chat) {
        return res.status(404).json({ error: "Chat not found" });
      }

      // Save user message
      const userMessage = await prisma.message.create({
        data: {
          chatId: chatId,
          role: "USER",
          content: messageText,
          senderId: user.id,
          ...(imageAttachments.length && {
            metadata: {
              imageAttachments,
            },
          }),
        },
      });
      const serializedUserMessage = serializeUserMessage(userMessage, user);

      // Update chat's updatedAt timestamp
      await prisma.chat.update({
        where: { id: chatId },
        data: { updatedAt: new Date() },
      });

      // Handle different chat types
      if (chat.type === "COACH") {
        if (useV2Coach) {
          logger.info(`Using coach v2 for user ${user.username}`);

          const payload = await runCoachV2MessagePipeline({
            user,
            chat,
            chatId,
            message: messageText,
            imageAttachments,
            serializedUserMessage,
            logLabel: "Coach v2 chat",
          });

          return res.json(payload);
        }

        // Get conversation history
        const history = await prisma.message.findMany({
          where: { chatId: chatId },
          orderBy: { createdAt: "desc" },
          take: 20,
        });
        history.reverse();

        // Get user's plans (include sessions for v2 agent)
        const plans = await prisma.plan.findMany({
          where: {
            userId: user.id,
            deletedAt: null,
            archivedAt: null,
            isPaused: false,
            OR: [
              { finishingDate: null },
              { finishingDate: { gt: new Date() } },
            ],
          },
          include: {
            activities: true,
          },
          orderBy: [{ createdAt: "desc" }],
        });

        const conversationHistory = toCoachConversationHistory(history);

        let aiResponse: {
          messageContent: string;
          planReplacements?: Array<{ textToReplace: string; planGoal: string }>;
          metricReplacement?: { textToReplace: string; metricTitle: string; rating: number } | null;
          planProposals?: Array<{ planId: string; planGoal: string; planEmoji: string | null; description: string; patch: unknown; operations?: unknown[]; status: null }>;
          userContextEventProposals?: Array<{
            title: string;
            description?: string | null;
            occurredAt?: string | null;
            endedAt?: string | null;
            source?: string | null;
            confidence?: number | null;
            status: null;
          }>;
          planCreationProposals?: Array<{
            goal: string;
            goalReason: string | null;
            notes?: string | null;
            emoji: string | null;
            outlineType?: "SPECIFIC" | "TIMES_PER_WEEK" | null;
            timesPerWeek: number | null;
            activities: Array<{ activityId?: string | null; title: string; measure: string; emoji: string; kind?: string | null }>;
            finishingDate?: string | null;
            milestones?: Array<{ description: string; date: string; criteria?: string | null }>;
            sessions?: Array<{
              activityTitle: string;
              date: string;
              quantity?: number | null;
              descriptiveGuide?: string | null;
            }>;
            description: string;
            status: null;
          }>;
          userRecommendations?: unknown;
          toolCalls?: Array<{ tool: string; args: unknown; result: unknown }>;
        };

        // Use the original coach (v1)
        const metrics = await prisma.metric.findMany({
          where: { userId: user.id },
          orderBy: [{ createdAt: "desc" }],
        });

        aiResponse = await aiService.generateCoachChatResponse({
          user: user,
          message: messageText,
          chatId: chatId,
          conversationHistory: conversationHistory,
          plans: plans,
          metrics: metrics,
        });

        // Save coach message
        const coachMessage = await prisma.message.create({
          data: {
            chatId: chatId,
            role: "COACH",
            content: aiResponse.messageContent,
            metadata: {
              planReplacements: aiResponse.planReplacements || [],
              metricReplacement: aiResponse.metricReplacement || null,
              planProposals: JSON.parse(JSON.stringify(aiResponse.planProposals || [])),
              userContextEventProposals: JSON.parse(JSON.stringify(aiResponse.userContextEventProposals || [])),
              planCreationProposals: JSON.parse(JSON.stringify(aiResponse.planCreationProposals || [])),
              userRecommendations: aiResponse.userRecommendations || null,
              ...(aiResponse.toolCalls && {
                toolCalls: JSON.parse(JSON.stringify(aiResponse.toolCalls)),
              }),
            },
          },
        });

        if ((aiResponse.planCreationProposals?.length || 0) > 0) {
          await cancelPendingPlanCreationProposals(chatId, [coachMessage.id]);
        }

        await prisma.chat.update({
          where: { id: chatId },
          data: { updatedAt: new Date() },
        });

        // Fire-and-forget: store exchange in long-term memory
        supermemoryService.addMemory(
          user.id,
          `user: ${messageText || "User attached an image for the coach to inspect."}\nassistant: ${aiResponse.messageContent}`,
          coachMessage.id
        );

        logger.info(
          `Coach chat - User: ${user.username}, Message: "${(messageText || "Image").substring(0, 50)}..."`
        );

        // Generate chat title if this is the first exchange
        if (!chat.title) {
          (async () => {
            try {
              const titlePrompt = `User: ${messageText || "User attached an image"}\nCoach: ${aiResponse.messageContent}`;
              const titleSystemPrompt =
                "You are a chat title generator. Create a very brief title (3-5 words max) that summarizes the topic of this conversation. " +
                "The title should be clear and concise. Only output the title, nothing else.";

              const generatedTitle = await aiService.generateText({
                prompt: titlePrompt,
                systemPrompt: titleSystemPrompt,
              });

              await prisma.chat.update({
                where: { id: chatId },
                data: { title: generatedTitle.trim() },
              });

              logger.info(
                `Generated title for chat ${chatId}: "${generatedTitle}"`
              );
            } catch (error) {
              logger.error("Error generating chat title:", error);
            }
          })();
        }

        // Resolve plans and metrics for response
        const stripEmojis = (text: string) => {
          return text
            .replace(
              /[\p{Emoji}\p{Emoji_Presentation}\p{Emoji_Modifier}\p{Emoji_Component}]/gu,
              ""
            )
            .trim();
        };

        const resolvedPlanReplacements =
          aiResponse.planReplacements
            ?.map((replacement) => {
              const plan = plans.find(
                (p) =>
                  p.goal.toLowerCase() === replacement.planGoal.toLowerCase()
              );
              return plan
                ? {
                    textToReplace: replacement.textToReplace,
                    plan: {
                      id: plan.id,
                      goal: plan.goal,
                      emoji: plan.emoji,
                    },
                  }
                : null;
            })
            .filter(Boolean) || [];

        let resolvedMetricReplacement: any = null;
        if (aiResponse.metricReplacement && !useV2Coach) {
          // Metric replacement is only available in v1
          const metrics = await prisma.metric.findMany({
            where: { userId: user.id },
            orderBy: [{ createdAt: "desc" }],
          });
          const aiMetricTitle = stripEmojis(
            aiResponse.metricReplacement.metricTitle
          ).toLowerCase();
          const metric = metrics.find(
            (m) => stripEmojis(m.title).toLowerCase() === aiMetricTitle
          );
          if (metric) {
            resolvedMetricReplacement = {
              textToReplace: aiResponse.metricReplacement.textToReplace,
              rating: aiResponse.metricReplacement.rating,
              metric: {
                id: metric.id,
                title: metric.title,
                emoji: metric.emoji,
              },
            };
          }
        }

        const serializedCoachMessage = {
          id: coachMessage.id,
          chatId: coachMessage.chatId,
          role: coachMessage.role,
          content: aiResponse.messageContent,
          planReplacements: resolvedPlanReplacements,
          metricReplacement: resolvedMetricReplacement,
          planProposals: aiResponse.planProposals || [],
          userContextEventProposals: aiResponse.userContextEventProposals || [],
          planCreationProposals: aiResponse.planCreationProposals || [],
          userRecommendations: aiResponse.userRecommendations || null,
          toolCalls: aiResponse.toolCalls || null,
          createdAt: coachMessage.createdAt,
        };

        return res.json({
          userMessage: serializedUserMessage,
          messages: [serializedUserMessage, serializedCoachMessage],
          message: serializedCoachMessage,
        });
      }

      // For DIRECT and GROUP chats, just acknowledge the message
      // (no AI response needed)
      logger.info(
        `${chat.type} chat message - User: ${user.username}, Chat: ${chatId}`
      );

      // Send notifications to other participants
      if (chat.type === "DIRECT" || chat.type === "GROUP") {
        const recipients = chat.participants.filter(
          (p) => p.userId !== user.id
        );
        const senderName = user.name || user.username || "Someone";
        const preview =
          messageText.length > 50
            ? messageText.substring(0, 50) + "..."
            : messageText || "Image";

        for (const recipient of recipients) {
          await notificationService.createAndProcessNotification({
            userId: recipient.userId,
            title: `New message from ${senderName}`,
            message: preview,
            type: "INFO",
            relatedId: chatId,
            relatedData: {
              chatId,
              senderId: user.id,
              senderName,
              senderPicture: user.picture,
            },
          });
        }
      }

      res.json({
        userMessage: serializedUserMessage,
        messages: [serializedUserMessage],
        message: serializedUserMessage,
      });
    } catch (error) {
      logger.error("Error sending message:", error);
      if (error instanceof RouteError) {
        return res.status(error.statusCode).json({ error: error.message });
      }
      res.status(500).json({ error: "Failed to send message" });
    }
  }
);

router.post(
  "/:chatId/messages/:messageId/rewrite/stream",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    let streamStarted = false;
    let clientClosed = false;
    let statusChatId: string | null = null;
    let statusUserMessageId: string | null = null;

    try {
      const user = req.user!;
      const { chatId, messageId } = req.params;
      const { message } = req.body;

      if (!message || typeof message !== "string" || !message.trim()) {
        return res.status(400).json({ error: "Message is required" });
      }

      res.setHeader("Content-Type", "text/event-stream");
      res.setHeader("Cache-Control", "no-cache, no-transform");
      res.setHeader("Connection", "keep-alive");
      res.flushHeaders?.();
      streamStarted = true;

      req.on("close", () => {
        clientClosed = true;
      });

      const sendStatus = (state: CoachResponseStatus) => {
        if (!clientClosed) {
          writeSseEvent(res, "status", { state });
        }
      };

      const rewriteContext = await prepareCoachMessageRewrite({
        user,
        chatId,
        messageId,
        message,
      });
      statusChatId = rewriteContext.chat.id;
      statusUserMessageId =
        typeof rewriteContext.serializedUserMessage.id === "string"
          ? rewriteContext.serializedUserMessage.id
          : null;

      if (statusUserMessageId) {
        await coachResponseStatusService.start({
          chatId: statusChatId,
          userMessageId: statusUserMessageId,
          status: "thinking",
        });
      }
      sendStatus("thinking");

      const payload = await runCoachV2MessagePipeline({
        user,
        chat: rewriteContext.chat,
        chatId: rewriteContext.chat.id,
        message,
        serializedUserMessage: rewriteContext.serializedUserMessage,
        conversationHistory: rewriteContext.conversationHistory,
        onStatus: (state) =>
          statusChatId && statusUserMessageId
            ? updateCoachResponseStatus({
                chatId: statusChatId,
                userMessageId: statusUserMessageId,
                state,
                sendStatus,
              })
            : sendStatus(state),
        logLabel: "Coach message rewritten stream",
      });

      if (statusChatId && statusUserMessageId) {
        await coachResponseStatusService.complete({
          chatId: statusChatId,
          userMessageId: statusUserMessageId,
        });
      }

      if (!clientClosed) {
        writeSseEvent(res, "done", payload);
        res.end();
      }
    } catch (error) {
      logger.error("Error streaming message rewrite:", error);
      if (statusChatId && statusUserMessageId) {
        await coachResponseStatusService.markError({
          chatId: statusChatId,
          userMessageId: statusUserMessageId,
          errorMessage:
            error instanceof Error ? error.message : "Failed to rewrite message",
        });
      }
      if (streamStarted && !clientClosed) {
        writeSseEvent(res, "error", {
          error: error instanceof Error ? error.message : "Failed to rewrite message",
        });
        res.end();
        return;
      }

      if (error instanceof RouteError) {
        return res.status(error.statusCode).json({ error: error.message });
      }
      res.status(500).json({ error: "Failed to rewrite message" });
    }
  }
);

router.post(
  "/:chatId/messages/:messageId/rewrite",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    try {
      const user = req.user!;
      const { chatId, messageId } = req.params;
      const { message } = req.body;

      if (!message || typeof message !== "string" || !message.trim()) {
        return res.status(400).json({ error: "Message is required" });
      }

      const rewriteContext = await prepareCoachMessageRewrite({
        user,
        chatId,
        messageId,
        message,
      });

      const payload = await runCoachV2MessagePipeline({
        user,
        chat: rewriteContext.chat,
        chatId: rewriteContext.chat.id,
        message,
        serializedUserMessage: rewriteContext.serializedUserMessage,
        conversationHistory: rewriteContext.conversationHistory,
        logLabel: "Coach message rewritten",
      });

      return res.json(payload);
    } catch (error) {
      logger.error("Error rewriting message:", error);
      if (error instanceof RouteError) {
        return res.status(error.statusCode).json({ error: error.message });
      }
      res.status(500).json({ error: "Failed to rewrite message" });
    }
  }
);

// Mark messages as read
router.post(
  "/:chatId/messages/mark-read",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    try {
      const user = req.user!;
      const { chatId } = req.params;
      const { messageIds } = req.body;

      if (!Array.isArray(messageIds) || messageIds.length === 0) {
        return res.status(400).json({ error: "messageIds array is required" });
      }

      // Verify user has access to this chat
      const chat = await prisma.chat.findFirst({
        where: {
          id: chatId,
          OR: [
            { userId: user.id, type: "COACH" },
            { participants: { some: { userId: user.id } } },
          ],
        },
      });

      if (!chat) {
        return res.status(404).json({ error: "Chat not found" });
      }

      // Update messages to READ status
      // For COACH chats, mark all non-user messages (senderId is null for coach messages)
      // For other chats, only mark messages not sent by the current user
      const result = await prisma.message.updateMany({
        where: {
          id: { in: messageIds },
          chatId: chatId,
          ...(chat.type === "COACH"
            ? { role: { not: "USER" } }
            : { senderId: { not: user.id } }),
          status: "SENT",
        },
        data: {
          status: "READ",
          readAt: new Date(),
        },
      });

      // Conclude week_recap notifications when their messages are read
      if (result.count > 0) {
        const markedMessages = await prisma.message.findMany({
          where: {
            id: { in: messageIds },
            chatId: chatId,
            status: "READ",
          },
          select: { id: true, metadata: true },
        });

        const weekRecapMessages = markedMessages.filter((msg) => {
          const metadata = msg.metadata as any;
          return metadata?.notificationType === "week_recap";
        });

        for (const msg of weekRecapMessages) {
          const metadata = msg.metadata as any;
          const proposals = metadata?.planProposals || [];
          const hasPendingProposals = proposals.some(
            (p: any) => !p.status
          );

          if (!hasPendingProposals) {
            await prisma.notification.updateMany({
              where: {
                userId: user.id,
                type: "COACH",
                title: "Weekly Recap",
                relatedId: chatId,
                status: { not: "CONCLUDED" },
              },
              data: {
                status: "CONCLUDED",
                concludedAt: new Date(),
              },
            });
            logger.info(
              `Concluded week_recap notifications for chat ${chatId}, user ${user.username}`
            );
          }
        }
      }

      logger.info(
        `Marked ${result.count} messages as read in chat ${chatId} for user ${user.username}`
      );
      res.json({ success: true, count: result.count });
    } catch (error) {
      logger.error("Error marking messages as read:", error);
      res.status(500).json({ error: "Failed to mark messages as read" });
    }
  }
);

// Create a direct message chat with another user
router.post(
  "/direct",
  requireAuth,
  async (
    req: AuthenticatedRequest,
    res: Response
  ): Promise<Response | void> => {
    try {
      const user = req.user!;
      const { userId: otherUserId } = req.body;

      if (!otherUserId || typeof otherUserId !== "string") {
        return res.status(400).json({ error: "userId is required" });
      }

      // Check if other user exists
      const otherUser = await prisma.user.findUnique({
        where: { id: otherUserId },
        select: {
          id: true,
          name: true,
          username: true,
          picture: true,
        },
      });

      if (!otherUser) {
        return res.status(404).json({ error: "User not found" });
      }

      // Check if users are friends (have an ACCEPTED connection)
      const connection = await prisma.connection.findFirst({
        where: {
          OR: [
            { fromId: user.id, toId: otherUserId, status: "ACCEPTED" },
            { fromId: otherUserId, toId: user.id, status: "ACCEPTED" },
          ],
        },
      });

      if (!connection) {
        return res.status(403).json({ error: "You can only message users you are connected with" });
      }

      // Check if a direct chat already exists between these users
      const existingChat = await prisma.chat.findFirst({
        where: {
          type: "DIRECT",
          AND: [
            {
              participants: {
                some: { userId: user.id },
              },
            },
            {
              participants: {
                some: { userId: otherUserId },
              },
            },
          ],
        },
        include: {
          participants: {
            include: {
              user: {
                select: {
                  id: true,
                  name: true,
                  username: true,
                  picture: true,
                },
              },
            },
          },
        },
      });

      if (existingChat) {
        logger.info(
          `Returning existing direct chat ${existingChat.id} between ${user.username} and ${otherUser.username}`
        );

        return res.json({
          chat: {
            id: existingChat.id,
            type: existingChat.type,
            title: existingChat.title,
            createdAt: existingChat.createdAt,
            updatedAt: existingChat.updatedAt,
            participants: existingChat.participants.map((p) => ({
              id: p.id,
              userId: p.user.id,
              name: p.user.name,
              username: p.user.username,
              picture: p.user.picture,
              joinedAt: p.joinedAt,
              leftAt: p.leftAt,
            })),
          },
        });
      }

      // Create new direct chat
      const chat = await prisma.chat.create({
        data: {
          type: "DIRECT",
          participants: {
            create: [{ userId: user.id }, { userId: otherUserId }],
          },
        },
        include: {
          participants: {
            include: {
              user: {
                select: {
                  id: true,
                  name: true,
                  username: true,
                  picture: true,
                },
              },
            },
          },
        },
      });

      logger.info(
        `Created direct chat ${chat.id} between ${user.username} and ${otherUser.username}`
      );

      res.json({
        chat: {
          id: chat.id,
          type: chat.type,
          title: chat.title,
          createdAt: chat.createdAt,
          updatedAt: chat.updatedAt,
          participants: chat.participants.map((p) => ({
            id: p.id,
            userId: p.user.id,
            name: p.user.name,
            username: p.user.username,
            picture: p.user.picture,
            joinedAt: p.joinedAt,
            leftAt: p.leftAt,
          })),
        },
      });
    } catch (error) {
      logger.error("Error creating direct chat:", error);
      res.status(500).json({ error: "Failed to create direct chat" });
    }
  }
);

export const chatsRouter: Router = router;
export default chatsRouter;
