/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DmsRouteImport } from './routes/dms'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as JoinPlanInvitationIdRouteImport } from './routes/join-plan.$invitationId'
import { Route as InsightsOnboardingRouteImport } from './routes/insights.onboarding'
import { Route as InsightsDashboardRouteImport } from './routes/insights.dashboard'
import { Route as FriendsUsernameRouteImport } from './routes/friends.$username'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsRoute = DmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinPlanInvitationIdRoute = JoinPlanInvitationIdRouteImport.update({
  id: '/join-plan/$invitationId',
  path: '/join-plan/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsOnboardingRoute = InsightsOnboardingRouteImport.update({
  id: '/insights/onboarding',
  path: '/insights/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsDashboardRoute = InsightsDashboardRouteImport.update({
  id: '/insights/dashboard',
  path: '/insights/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsUsernameRoute = FriendsUsernameRouteImport.update({
  id: '/friends/$username',
  path: '/friends/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ai': typeof AiRoute
  '/dms': typeof DmsRoute
  '/download': typeof DownloadRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/upgrade': typeof UpgradeRoute
  '/friends/$username': typeof FriendsUsernameRoute
  '/insights/dashboard': typeof InsightsDashboardRoute
  '/insights/onboarding': typeof InsightsOnboardingRoute
  '/join-plan/$invitationId': typeof JoinPlanInvitationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ai': typeof AiRoute
  '/dms': typeof DmsRoute
  '/download': typeof DownloadRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/upgrade': typeof UpgradeRoute
  '/friends/$username': typeof FriendsUsernameRoute
  '/insights/dashboard': typeof InsightsDashboardRoute
  '/insights/onboarding': typeof InsightsOnboardingRoute
  '/join-plan/$invitationId': typeof JoinPlanInvitationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ai': typeof AiRoute
  '/dms': typeof DmsRoute
  '/download': typeof DownloadRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/upgrade': typeof UpgradeRoute
  '/friends/$username': typeof FriendsUsernameRoute
  '/insights/dashboard': typeof InsightsDashboardRoute
  '/insights/onboarding': typeof InsightsOnboardingRoute
  '/join-plan/$invitationId': typeof JoinPlanInvitationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/ai'
    | '/dms'
    | '/download'
    | '/onboarding'
    | '/plans'
    | '/search'
    | '/signin'
    | '/signout'
    | '/upgrade'
    | '/friends/$username'
    | '/insights/dashboard'
    | '/insights/onboarding'
    | '/join-plan/$invitationId'
    | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/ai'
    | '/dms'
    | '/download'
    | '/onboarding'
    | '/plans'
    | '/search'
    | '/signin'
    | '/signout'
    | '/upgrade'
    | '/friends/$username'
    | '/insights/dashboard'
    | '/insights/onboarding'
    | '/join-plan/$invitationId'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/ai'
    | '/dms'
    | '/download'
    | '/onboarding'
    | '/plans'
    | '/search'
    | '/signin'
    | '/signout'
    | '/upgrade'
    | '/friends/$username'
    | '/insights/dashboard'
    | '/insights/onboarding'
    | '/join-plan/$invitationId'
    | '/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AiRoute: typeof AiRoute
  DmsRoute: typeof DmsRoute
  DownloadRoute: typeof DownloadRoute
  OnboardingRoute: typeof OnboardingRoute
  PlansRoute: typeof PlansRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  UpgradeRoute: typeof UpgradeRoute
  FriendsUsernameRoute: typeof FriendsUsernameRoute
  InsightsDashboardRoute: typeof InsightsDashboardRoute
  InsightsOnboardingRoute: typeof InsightsOnboardingRoute
  JoinPlanInvitationIdRoute: typeof JoinPlanInvitationIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms': {
      id: '/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof DmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-plan/$invitationId': {
      id: '/join-plan/$invitationId'
      path: '/join-plan/$invitationId'
      fullPath: '/join-plan/$invitationId'
      preLoaderRoute: typeof JoinPlanInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/onboarding': {
      id: '/insights/onboarding'
      path: '/insights/onboarding'
      fullPath: '/insights/onboarding'
      preLoaderRoute: typeof InsightsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/dashboard': {
      id: '/insights/dashboard'
      path: '/insights/dashboard'
      fullPath: '/insights/dashboard'
      preLoaderRoute: typeof InsightsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$username': {
      id: '/friends/$username'
      path: '/friends/$username'
      fullPath: '/friends/$username'
      preLoaderRoute: typeof FriendsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AiRoute: AiRoute,
  DmsRoute: DmsRoute,
  DownloadRoute: DownloadRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  UpgradeRoute: UpgradeRoute,
  FriendsUsernameRoute: FriendsUsernameRoute,
  InsightsDashboardRoute: InsightsDashboardRoute,
  InsightsOnboardingRoute: InsightsOnboardingRoute,
  JoinPlanInvitationIdRoute: JoinPlanInvitationIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
