import { test, expect } from "@playwright/test";
const API="http://127.0.0.1:4317";
for (const theme of ["DARK","LIGHT"]) test(`people search handles names, typos, empty results and back in ${theme}`,async({page,request})=>{
 await request.post(`${API}/__reset`);
 await request.post(`${API}/__people-search`);
 await request.patch(`${API}/users/user`,{headers:{Authorization:"Bearer local-e2e-token"},data:{themeMode:theme,themeBaseColor:"AMBER"}});
 await page.goto("/search");
 const input=page.getByRole("textbox",{name:"Search people"});
 const people=page.getByRole("button",{name:/^View @/});
 await expect(people).toHaveCount(2);
 expect(await people.evaluateAll(nodes=>nodes.map(node=>node.getAttribute("aria-label")))).toEqual(["View @barbara's profile","View @liocas's profile"]);
 await input.fill("Lia");
 const lia=page.getByRole("button",{name:"View @liocas's profile",exact:true});
 await expect(lia).toBeVisible();
 await expect(lia).toContainText("Lia Borges");
 await page.screenshot({path:`test-results/people-search-${theme}.png`});
 await input.fill("liocsa");
 await expect(lia).toBeVisible();
 await lia.click();
 await expect(page).toHaveURL(/profile\/liocas/);
 await page.getByRole("button",{name:"Back",exact:true}).click();
 await expect(input).toHaveValue("liocsa");
 await input.fill("zzzzzz");
 await expect(page.getByText("No matching people",{exact:true})).toBeVisible();
 await expect(page.getByRole("button",{name:"Back",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Clear search",exact:true}).click();
 await expect(input).toHaveValue("");
 await page.goto("/profile/nonexistent-user");
 await expect(page.getByText("User not found",{exact:true})).toBeVisible();
 await expect(page.getByRole("button",{name:"Back",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Back",exact:true}).click();
 await expect(page.getByText("User not found",{exact:true})).not.toBeVisible();
});
test("a failed search preserves the query and navigation",async({page,request})=>{
 await request.post(`${API}/__reset`);await request.post(`${API}/__people-search`);
 await page.goto("/search");
 let failing=true;
 await page.route(`${API}/users/search-users/Lia`,route=>failing?route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({error:"Search unavailable"})}):route.continue());
 await page.getByRole("textbox",{name:"Search people"}).fill("Lia");
 await expect(page.getByRole("button",{name:"Try again",exact:true})).toBeVisible();
 await expect(page.getByRole("textbox",{name:"Search people"})).toHaveValue("Lia");
 await expect(page.getByRole("button",{name:"Back",exact:true})).toBeVisible();
 failing=false;
 await page.getByRole("button",{name:"Try again",exact:true}).click();
 await expect(page.getByRole("button",{name:"View @liocas's profile",exact:true})).toBeVisible();
});
