import { test, expect } from "@playwright/test";
const API = "http://127.0.0.1:4317";
for (const theme of ["DARK", "LIGHT"]) test(`settings subdrawers match the PWA in ${theme}`, async ({ page, request }) => {
  await request.post(`${API}/__reset`); await request.patch(`${API}/users/user`, { headers: { Authorization: "Bearer local-e2e-token" }, data: { themeMode: theme, themeBaseColor: "AMBER" } });
  await page.goto("/settings");
  await page.getByRole("button", { name: "Color Palette", exact: true }).click();
  await expect(page.getByTestId("settings-palettes").getByRole("button")).toHaveCount(7);
  await expect(page.getByTestId("settings-palettes").locator('[data-testid^="palette-swatch-"]')).toHaveCount(18);
  await page.waitForTimeout(400); await page.screenshot({ path: `test-results/settings-palettes-${theme}.png` });
  await request.post(`${API}/__fail`, { data: { path: "/users/user" } });
  await page.getByRole("button", { name: "Violet", exact: true }).click();
  await expect(page.getByText("Simulated network failure. Please try again.")).toBeVisible();
  await page.getByRole("button", { name: "Violet", exact: true }).click();
  await expect(page.getByRole("button", { name: "Color Palette", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Theme Mode", exact: true }).click();
  await expect(page.getByText("Match system preference")).toBeVisible();
  await page.waitForTimeout(400); await page.screenshot({ path: `test-results/settings-theme-${theme}.png` });
  await page.getByRole("button", { name: "Back to Settings" }).click();
  await page.getByRole("button", { name: "Integrations & API Keys" }).click();
  await page.waitForTimeout(400); await page.screenshot({ path: `test-results/settings-integrations-${theme}.png` });
  await page.getByRole("button", { name: "API keys", exact: true }).click();
  await expect(page.getByText("1. Create an API key")).toBeVisible();
  await page.getByRole("button", { name: "Back to Integrations" }).click();
  await page.getByRole("button", { name: "Apple Health", exact: true }).click();
  await expect(page.getByText("Workouts and sleep, together")).toBeVisible();
  await page.getByRole("button", { name: "Back to Integrations" }).click();
  await page.getByRole("button", { name: "Back to Settings" }).click();
  await page.getByRole("button", { name: "User Settings", exact: true }).click();
  await expect(page.getByText("Read only", { exact: true })).toHaveCount(2);
  await page.waitForTimeout(400); await page.screenshot({ path: `test-results/settings-user-${theme}.png` });
  await page.getByRole("button", { name: "Full Name", exact: true }).click();
  await page.getByRole("textbox", { name: "Full Name", exact: true }).fill("New name");
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByText("New name", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Delete Account", exact: true }).click();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  const state = await (await request.get(`${API}/__state`)).json();
  expect(state.user.themeBaseColor).toBe("VIOLET");
  expect(state.requests.filter((r: any) => r.method === "DELETE")).toHaveLength(0);
});
