name: Daily Tests

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8am UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install backend-node dependencies
        working-directory: apps/backend-node
        run: pnpm install

      - name: Generate prisma types
        working-directory: packages/prisma
        run: pnpm db:generate

      - name: Run backend-node tests
        id: backend_node_tests
        continue-on-error: true
        working-directory: apps/backend-node
        env:
          ENVIRONMENT: "production"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          pnpm test:ci 2>&1 | tee test_output.txt
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "Tests failed. Sending failure notification..."
            tsx scripts/send_telegram_message.ts "❌ Backend-Node Tests Failed. Check GH logs for details."
            exit 1
          else
            echo "Tests passed. Sending success notification..."
            tsx scripts/send_telegram_message.ts "✅ Backend-Node Tests Passed"
          fi

      - name: Upload backend-node test results
        if: steps.backend_node_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: backend-node-test-output
          path: apps/backend-node/test_output.txt
          retention-days: 3

      - name: Check test results
        if: always()
        run: |
          if [ "${{ steps.backend_node_tests.outcome }}" != "success" ]; then
            exit 1
          fi 