name: Deploy Backend
on:
  workflow_call:

jobs:
  deploy-flightcontrol:
    uses: ./.github/workflows/deploy-flightcontrol.yml
    secrets: inherit

  deploy-aws:
    # needs: deploy-flightcontrol
    uses: ./.github/workflows/deploy-to-aws.yml
    secrets: inherit
