name: Deploy to Sandbox

on:
  workflow_call:
jobs:
  deploy-cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy CDK
        env:
          ENVIRONMENT: production
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SHARED_ENCRYPTION_KEY: ${{ secrets.SHARED_ENCRYPTION_KEY }}
          MONGO_DB_CONNECTION_STRING: ${{ secrets.MONGO_DB_CONNECTION_STRING }}
          CLERK_JWT_PUBLIC_KEY: ${{ secrets.CLERK_JWT_PUBLIC_KEY }}
          SVIX_SECRET: ${{ secrets.SVIX_SECRET }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
          JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LOOPS_API_KEY: ${{ secrets.LOOPS_API_KEY }}
          # Axiom Configuration
          AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
          OTEL_ENABLED: "true"
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "https://api.axiom.co/v1/traces"
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "https://api.axiom.co/v1/logs"
          AXIOM_ORG_ID: "tracking.software"
          AXIOM_DATASET: "app.tracking.so"
          AXIOM_BATCH_SIZE: "50"
          
        run: |
          cd aws-infrastructure
          yarn
          yarn bootstrap
          yarn deploy