name: Deploy Backend Status
on:
  deployment_status:

jobs:
  flightcontrol-status:
    if: github.event.deployment_status.state == 'success' || github.event.deployment_status.state == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Check deployment status
        run: |
          echo "Deployment status: ${{ github.event.deployment_status.state }}"
          echo "Environment: ${{ github.event.deployment.environment }}"
          echo "Deployment URL: ${{ github.event.deployment_status.target_url }}"
          
          if [ "${{ github.event.deployment_status.state }}" == "success" ]; then
            echo "✅ Backend deployment succeeded!"
          else
            echo "❌ Backend deployment failed!"
            exit 1
          fi
