name: Deploy all to Production
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit

  deploy-frontend:
    uses: ./.github/workflows/deploy-to-vercel.yml
    with:
        deploy_url: https://api.vercel.com/v1/integrations/deploy/prj_7jVbMD4AqXfMDHlPGcV2KoBv4Xta/9wjHhsX0a1
    secrets: inherit
